# Generated by Django 2.2.5 on 2019-11-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_blog', '0002_auto_20191108_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='md',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
